package info.kg6jay.moredyes;

/** Generated by tools/make_textures.py: where each texture is in the sheet moredyes/terrain.png. */
public final class Textures {

    public static final String SHEET = "/moredyes/terrain.png";
    public static final String CHEST = "/moredyes/chest.png";
    public static final String LARGE_CHEST = "/moredyes/largechest.png";

    public static final int WOOL = 0;
    public static final int STONE = 1;
    public static final int COBBLE = 2;
    public static final int STONEBRICK = 4;
    public static final int STONEBRICK_CARVED = 5;
    public static final int STONEBRICK_CRACKED = 6;
    public static final int OBSIDIAN = 7;
    public static final int SOULSAND = 8;
    public static final int QUARTZ_TOP = 9;
    public static final int QUARTZ_SIDE = 10;
    public static final int QUARTZ_BOTTOM = 11;
    public static final int CLAY = 12;
    public static final int HARDENED_CLAY = 13;
    public static final int COAL = 14;
    public static final int GLOWSTONE = 15;
    public static final int LAPIS = 16;
    public static final int REDSTONE = 17;
    public static final int PLANK = 18;
    public static final int BRICK = 19;
    public static final int SAND = 20;
    public static final int SANDSTONE_TOP = 21;
    public static final int SANDSTONE_SIDE = 22;
    public static final int SANDSTONE_BOTTOM = 23;
    public static final int BOOKSHELF = 24;
    public static final int WORKBENCH_TOP = 25;
    public static final int WORKBENCH_SIDE = 26;
    public static final int WORKBENCH_FRONT = 27;
    public static final int LOG_TOP = 28;
    public static final int LOG_BARK = 29;
    public static final int LEAF = 30;
    public static final int GLASS_CLEAR = 31;
    public static final int GLASS_PANE = 32;
    public static final int GLASS_FOGGY = 33;
    public static final int DIORITE = 34;
    public static final int SMOOTH_STONE = 35;
    public static final int SMOOTH_SANDSTONE = 36;
    public static final int SMOOTH_QUARTZ = 37;
    public static final int CUT_SANDSTONE_TOP = 38;
    public static final int CUT_SANDSTONE_SIDE = 39;
    public static final int CUT_SANDSTONE_BOTTOM = 40;
    public static final int MOSSY_COBBLE = 41;
    public static final int MOSSY_STONEBRICK = 42;
    public static final int NETHER_BRICK = 43;
    public static final int GRANITE = 44;
    public static final int ANDESITE = 45;
    public static final int POLISHED_GRANITE = 46;
    public static final int POLISHED_DIORITE = 47;
    public static final int POLISHED_ANDESITE = 48;
    public static final int CONCRETE = 49;
    public static final int CONCRETE_POWDER = 50;
    public static final int SOUL_SOIL = 51;
    public static final int BASALT_TOP = 52;
    public static final int BASALT_SIDE = 53;
    public static final int BASALT_BOTTOM = 54;
    public static final int POLISHED_BASALT_TOP = 55;
    public static final int POLISHED_BASALT_SIDE = 56;
    public static final int POLISHED_BASALT_BOTTOM = 57;
    public static final int CRACKED_NETHER_BRICK = 58;
    public static final int CHISELED_NETHER_BRICK = 59;
    public static final int END_STONE_BRICK = 60;
    public static final int BONE_BLOCK_TOP = 61;
    public static final int BONE_BLOCK_SIDE = 62;
    public static final int BONE_BLOCK_BOTTOM = 63;
    public static final int GLAZED_TERRACOTTA = 64;
    public static final int NETHERITE_BLOCK = 65;
    public static final int CRYING_OBSIDIAN = 66;
    public static final int IRON_TRAPDOOR = 67;
    public static final int CHAIN = 68;
    public static final int CORNFLOWER_PETALS = 69;
    public static final int CORNFLOWER_STEM = 70;
    public static final int TULIP_PETALS = 71;
    public static final int TULIP_STEM = 72;
    public static final int SAPLING_LEAVES = 73;
    public static final int SAPLING_TRUNK = 74;
    public static final int DYE = 75;

    private Textures() {}
}
